In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import itertools
import os

In [2]:
# Import the global report card performance file (source file detailed in write-up Section 2.1)
scores = pd.read_csv("Resources/GlobalReportCard.csv", low_memory=False)

scoredf = pd.DataFrame(scores)

# List of the column names, counts and info types in the file
scoredf.head()

,NCES District ID,District Name,Public District Name,"Charter (1=Yes, 0=No)",City,County,Zip,State,State Abbreviation,2009 Total PK-12 Enrollment,...,2007 Math Percentile if District was in Singapore,2008 Math Percentile if District was in Singapore**,2009 Math Percentile if District was in Singapore**,2009 Reading Percentile if District was in Singapore**,2007 Math Percentile if District was in Switzerland,2008 Math Percentile if District was in Switzerland**,2009 Math Percentile if District was in Switzerland**,2007 Reading Percentile if District was in Switzerland,2008 Reading Percentile if District was in Switzerland**,2009 Reading Percentile if District was in Switzerland**
0,2509390.0,PELHAM,Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,11700.00%,...,82.77%,84.42%,85.96%,80.98%,91.87%,92.03%,92.18%,89.09%,88.66%,88.23%
1,2501920.0,AMHERST-PELHAM,Amherst-Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,173100.00%,...,54.09%,56.76%,59.40%,73.48%,69.11%,69.72%,70.30%,83.17%,82.72%,82.28%
2,2501890.0,AMHERST,Amherst,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,138200.00%,...,43.07%,45.76%,48.46%,63.92%,58.07%,58.82%,59.56%,74.77%,74.39%,74.00%
3,2500001.0,QUABBIN,Quabbin,0,BARRE,WORCESTER,1005.0,Massachusetts,MA,312500.00%,...,33.68%,36.20%,38.79%,56.12%,47.64%,48.49%,49.32%,67.29%,67.00%,66.72%
4,2502430.0,BELCHERTOWN,Belchertown,0,BELCHERTOWN,HAMPSHIRE,1007.0,Massachusetts,MA,264900.00%,...,34.20%,36.73%,39.33%,56.73%,48.24%,49.09%,49.91%,67.90%,67.60%,67.31%

In [3]:
# Create a new performance Dataframe from file with only those columns needed & columns renamed

perfdata = scoredf.filter(['NCES District ID', 'District Name', 'Public District Name','Charter (1=Yes, 0=No)', 'City', 'County', 'Zip', 'State',       
                'State Abbreviation','2009 National Math Percentile**','2009 National Reading Percentile**'], axis = 1)

perfdata = perfdata.rename(columns={'2009 National Math Percentile**': 'MathPercentile', '2009 National Reading Percentile**': 'ReadPercentile'})

perfdata.head()

,NCES District ID,District Name,Public District Name,"Charter (1=Yes, 0=No)",City,County,Zip,State,State Abbreviation,MathPercentile,ReadPercentile
0,2509390.0,PELHAM,Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,97.25%,87.80%
1,2501920.0,AMHERST-PELHAM,Amherst-Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,84.65%,81.89%
2,2501890.0,AMHERST,Amherst,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,76.61%,73.73%
3,2500001.0,QUABBIN,Quabbin,0,BARRE,WORCESTER,1005.0,Massachusetts,MA,67.83%,66.60%
4,2502430.0,BELCHERTOWN,Belchertown,0,BELCHERTOWN,HAMPSHIRE,1007.0,Massachusetts,MA,68.37%,67.18%

In [4]:
# Cleans out the data so districts with no data for scores are removed

perfdata = perfdata.loc[perfdata["MathPercentile"] != 'No Data Available']
perfdata = perfdata.loc[perfdata["ReadPercentile"] != 'No Data Available']

perfdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13589 entries, 0 to 15583
Data columns (total 11 columns):
NCES District ID         13587 non-null float64
District Name            13589 non-null object
Public District Name     13589 non-null object
Charter (1=Yes, 0=No)    13589 non-null object
City                     13589 non-null object
County                   13589 non-null object
Zip                      13589 non-null float64
State                    13589 non-null object
State Abbreviation       13587 non-null object
MathPercentile           13589 non-null object
ReadPercentile           13589 non-null object
dtypes: float64(2), object(9)
memory usage: 1.2+ MB

In [5]:
# strip and change type for performance data columns
perfdata['MathPercentile'] = perfdata['MathPercentile'].str.rstrip('%')
perfdata['ReadPercentile'] = perfdata['ReadPercentile'].str.rstrip('%')

perfdata['MathPercentile'] = perfdata['MathPercentile'].astype('float')
perfdata['ReadPercentile'] = perfdata['ReadPercentile'].astype('float')

perfdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13589 entries, 0 to 15583
Data columns (total 11 columns):
NCES District ID         13587 non-null float64
District Name            13589 non-null object
Public District Name     13589 non-null object
Charter (1=Yes, 0=No)    13589 non-null object
City                     13589 non-null object
County                   13589 non-null object
Zip                      13589 non-null float64
State                    13589 non-null object
State Abbreviation       13587 non-null object
MathPercentile           13589 non-null float64
ReadPercentile           13589 non-null float64
dtypes: float64(4), object(7)
memory usage: 1.2+ MB

In [6]:
# Import the district information file (source file detailed in write-up Section 2.2)
district = pd.read_csv("Resources/Combined District Table.csv")

districtdf = pd.DataFrame(district)

# List of the column names, counts and info types in the file
districtdf.head()

,LEAID,LEA_NAME,LEA_TYPE_TEXT,STABR,STATENAME,LCITY,LSTATE,LZIP,GSLO,GSHI,...,TOTTCH,TOTGUI,MEMBER,AM,AS,HI,BL,WH,HP,TR
0,200180,Anchorage School District,Regular local school district that is NOT a co...,AK,ALASKA,Anchorage,AK,99504,PK,12.0,...,2816,114,48324,4200,5147,5492,2780,20739,2689,7277
1,200800,Chugach School District,Regular local school district that is NOT a co...,AK,ALASKA,Anchorage,AK,99507,PK,12.0,...,15,0,363,48,9,21,1,248,11,25
2,200010,Aleutian Region School District,Regular local school district that is NOT a co...,AK,ALASKA,Anchorage,AK,99518,PK,12.0,...,4,0,35,14,2,9,0,3,4,3
3,200004,Yupiit School District,Regular local school district that is NOT a co...,AK,ALASKA,Akiachak,AK,99551,PK,12.0,...,38,3,461,448,0,1,0,8,0,4
4,200760,Kuspuk School District,Regular local school district that is NOT a co...,AK,ALASKA,Aniak,AK,99557,PK,12.0,...,30,1,410,400,0,0,0,10,0,0

In [7]:
# Create a new district demographic Dataframe from file with only those columns needed & columns renamed
districtdata = districtdf.filter(['LEAID', 'SCH', 'TOTTCH', 'MEMBER'])

# Rename columns needed
districtdata = districtdata.rename(columns={'LEAID': 'NCES District ID', 'SCH': "Total Schools", 'TOTTCH': 'Total Teachers', 'MEMBER': 'Total Students'})

districtdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17593 entries, 0 to 17592
Data columns (total 4 columns):
NCES District ID    17593 non-null int64
Total Schools       17593 non-null int64
Total Teachers      17593 non-null int64
Total Students      17593 non-null int64
dtypes: int64(4)
memory usage: 549.9 KB

In [8]:
# Remove districts where the school, teacher and/or student count is 0 or less

districtdata_notzero = districtdata[districtdata > 0].dropna()

districtdata.head()

   NCES District ID  Total Schools  Total Teachers  Total Students
0            200180             98            2816           48324
1            200800              4              15             363
2            200010              2               4              35
3            200004              3              38             461
4            200760              9              30             410

In [9]:
# Merge the performance and district files using the NCES District ID

ratiodata = perfdata.merge(districtdata_notzero, on = 'NCES District ID')

ratiodata.head()

,NCES District ID,District Name,Public District Name,"Charter (1=Yes, 0=No)",City,County,Zip,State,State Abbreviation,MathPercentile,ReadPercentile,Total Schools,Total Teachers,Total Students
0,2509390.0,PELHAM,Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,97.25,87.80,1.0,11.0,125.0
1,2501920.0,AMHERST-PELHAM,Amherst-Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,84.65,81.89,2.0,117.0,1391.0
2,2501890.0,AMHERST,Amherst,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,76.61,73.73,3.0,122.0,1183.0
3,2500001.0,QUABBIN,Quabbin,0,BARRE,WORCESTER,1005.0,Massachusetts,MA,67.83,66.60,8.0,159.0,2428.0
4,2502430.0,BELCHERTOWN,Belchertown,0,BELCHERTOWN,HAMPSHIRE,1007.0,Massachusetts,MA,68.37,67.18,5.0,167.0,2380.0

In [10]:
# FOR THE STUDENT/TEACHER RATIO - Calculate student/teacher ratio by NCES district 

StuTch_ratio = ratiodata.set_index('NCES District ID')['Total Students']/ratiodata.set_index('NCES District ID')['Total Teachers']

ratiodf = pd.DataFrame({'Student/Teacher Ratio': StuTch_ratio})

ratiodf.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 12683 entries, 2509390.0 to 200810.0
Data columns (total 1 columns):
Student/Teacher Ratio    12683 non-null float64
dtypes: float64(1)
memory usage: 198.2 KB

In [11]:
# Merge the ratiodata and ratiodf using the NCES District ID

final_ratio = pd.merge(ratiodata, ratiodf, on = 'NCES District ID')

final_ratio.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12685 entries, 0 to 12684
Data columns (total 15 columns):
NCES District ID         12685 non-null float64
District Name            12685 non-null object
Public District Name     12685 non-null object
Charter (1=Yes, 0=No)    12685 non-null object
City                     12685 non-null object
County                   12685 non-null object
Zip                      12685 non-null float64
State                    12685 non-null object
State Abbreviation       12685 non-null object
MathPercentile           12685 non-null float64
ReadPercentile           12685 non-null float64
Total Schools            12685 non-null float64
Total Teachers           12685 non-null float64
Total Students           12685 non-null float64
Student/Teacher Ratio    12685 non-null float64
dtypes: float64(8), object(7)
memory usage: 1.5+ MB

In [12]:
finalratiodf = pd.DataFrame(final_ratio)
finalratiodf["Zip"] = finalratiodf["Zip"].astype('int')

#export cleaned dataframe as csv file
finalratiodf.to_csv("clean_data.csv")
finalratiodf.head()

,NCES District ID,District Name,Public District Name,"Charter (1=Yes, 0=No)",City,County,Zip,State,State Abbreviation,MathPercentile,ReadPercentile,Total Schools,Total Teachers,Total Students,Student/Teacher Ratio
0,2509390.0,PELHAM,Pelham,0,AMHERST,HAMPSHIRE,1002,Massachusetts,MA,97.25,87.80,1.0,11.0,125.0,11.363636
1,2501920.0,AMHERST-PELHAM,Amherst-Pelham,0,AMHERST,HAMPSHIRE,1002,Massachusetts,MA,84.65,81.89,2.0,117.0,1391.0,11.888889
2,2501890.0,AMHERST,Amherst,0,AMHERST,HAMPSHIRE,1002,Massachusetts,MA,76.61,73.73,3.0,122.0,1183.0,9.696721
3,2500001.0,QUABBIN,Quabbin,0,BARRE,WORCESTER,1005,Massachusetts,MA,67.83,66.60,8.0,159.0,2428.0,15.270440
4,2502430.0,BELCHERTOWN,Belchertown,0,BELCHERTOWN,HAMPSHIRE,1007,Massachusetts,MA,68.37,67.18,5.0,167.0,2380.0,14.251497

In [13]:
# Import the income information file (source file detailed in write-up Section 2.3)
incomes = pd.read_csv("Resources/MedianIncomeZip.csv")

incomedf = pd.DataFrame(incomes)
incomedf = incomedf.loc[incomedf["Zip"] > 0]
incomedf["Zip"] = incomedf["Zip"].astype('int')
incomedf.rename(columns = {' HC03_EST_VC02 Median income (dollars); Estimate; Households ': "Income"}, inplace = True)
#Cleans out 
incomedf['Income'] = incomedf['Income'].str.lstrip(" $")
incomedf['Income'] = incomedf['Income'].str.rstrip(" ")

incomedf["Income"] = incomedf["Income"].replace( '[,]','', regex=True )
incomedf["Income"] = incomedf["Income"].astype("float")
incomedf.head()

  GEO.display-label Geography  Zip   Income
0                       ZCTA5  601  11757.0
1                       ZCTA5  602  16190.0
2                       ZCTA5  603  16645.0
3                       ZCTA5  606  13387.0
4                       ZCTA5  610  18741.0

In [14]:
# FOR THE SPECIFIC INCOME QUESTION ONLY, merge performance and income dataframes (to eliminate districts where there is no income data)

incperfdata = perfdata.merge(incomedf, on = "Zip")
incperfdata["Income"] = incperfdata["Income"].astype('float')
incperfdata = incperfdata.loc[incperfdata["Income"] > 0]
incperfdata.to_csv("IncomePerfData.csv")
incperfdata

,NCES District ID,District Name,Public District Name,"Charter (1=Yes, 0=No)",City,County,Zip,State,State Abbreviation,MathPercentile,ReadPercentile,GEO.display-label Geography,Income
0,2509390.0,PELHAM,Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,97.25,87.80,ZCTA5,52379.0
1,2501920.0,AMHERST-PELHAM,Amherst-Pelham,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,84.65,81.89,ZCTA5,52379.0
2,2501890.0,AMHERST,Amherst,0,AMHERST,HAMPSHIRE,1002.0,Massachusetts,MA,76.61,73.73,ZCTA5,52379.0
3,2500001.0,QUABBIN,Quabbin,0,BARRE,WORCESTER,1005.0,Massachusetts,MA,67.83,66.60,ZCTA5,70325.0
4,2502430.0,BELCHERTOWN,Belchertown,0,BELCHERTOWN,HAMPSHIRE,1007.0,Massachusetts,MA,68.37,67.18,ZCTA5,86165.0
5,2503660.0,CHICOPEE,Chicopee,0,CHICOPEE,HAMPDEN,1020.0,Massachusetts,MA,50.31,47.30,ZCTA5,58780.0
6,2500014.0,CHESTERFIELD-GOSHEN,Chesterfield-Goshen,0,WESTHAMPTON,HAMPSHIRE,1027.0,Massachusetts,MA,74.90,72.47,ZCTA5,63699.0
7,2512990.0,WILLIAMSBURG,Williamsburg,0,WESTHAMPTON,HAMPSHIRE,1027.0,Massachusetts,MA,70.89,70.00,ZCTA5,63699.0
8,2505740.0,HAMPSHIRE,Hampshire,0,WESTHAMPTON,HAMPSHIRE,1027.0,Massachusetts,MA,64.57,75.51,ZCTA5,63699.0
9,2504590.0,EASTHAMPTON,Easthampton,0,EASTHAMPTON,HAMPSHIRE,1027.0,Massachusetts,MA,64.28,58.24,ZCTA5,63699.0
10,2510950.0,SOUTHAMPTON,Southampton,0,WESTHAMPTON,HAMPSHIRE,1027.0,Massachusetts,MA,60.10,67.90,ZCTA5,63699.0
11,2512690.0,WESTHAMPTON,Westhampton,0,WESTHAMPTON,HAMPSHIRE,1027.0,Massachusetts,MA,51.58,51.82,ZCTA5,63699.0
12,2504500.0,EAST LONGMEADOW,East Longmeadow,0,EAST LONGMEADOW,HAMPDEN,1028.0,Massachusetts,MA,76.47,76.23,ZCTA5,85221.0
13,2501800.0,AGAWAM,Agawam,0,FEEDING HILLS,HAMPDEN,1030.0,Massachusetts,MA,72.73,65.80,ZCTA5,71716.0
14,2505400.0,GRANBY,Granby,0,GRANBY,HAMPSHIRE,1033.0,Massachusetts,MA,72.26,66.97,ZCTA5,89965.0
15,2505580.0,HADLEY,Hadley,0,HADLEY,HAMPSHIRE,1035.0,Massachusetts,MA,76.46,70.68,ZCTA5,58953.0
16,2500044.0,PIONEER VALLEY PERFORMING ARTS CHARTER PUBLIC ...,Pioneer Valley,1,HADLEY,HAMPSHIRE,1035.0,Massachusetts,MA,76.32,91.18,ZCTA5,58953.0
17,2505940.0,HATFIELD,Hatfield,0,HATFIELD,HAMPSHIRE,1038.0,Massachusetts,MA,69.17,72.24,ZCTA5,67096.0
18,2500031.0,HILLTOWN COOPERATIVE CHARTER PUBLIC (DISTRICT),Hilltown Cooperative,1,HAYDENVILLE,HAMPSHIRE,1039.0,Massachusetts,MA,84.56,81.64,ZCTA5,80000.0
19,2506270.0,HOLYOKE,Holyoke,0,HOLYOKE,HAMPDEN,1040.0,Massachusetts,MA,29.93,26.02,ZCTA5,37954.0
20,2500087.0,HOLYOKE COMMUNITY CHARTER (DISTRICT),Holyoke Community,1,HOLYOKE,HAMPDEN,1040.0,Massachusetts,MA,27.81,23.12,ZCTA5,37954.0
21,2505160.0,GATEWAY,Gateway,0,HUNTINGTON,HAMPSHIRE,1050.0,Massachusetts,MA,52.36,53.80,ZCTA5,68869.0
22,2507050.0,LUDLOW,Ludlow,0,LUDLOW,HAMPDEN,1056.0,Massachusetts,MA,68.48,65.13,ZCTA5,67715.0
23,2508040.0,MONSON,Monson,0,MONSON,HAMPDEN,1057.0,Massachusetts,MA,60.09,65.36,ZCTA5,78986.0
24,2508850.0,NORTHAMPTON,Northampton,0,NORTHAMPTON,HAMPSHIRE,1060.0,Massachusetts,MA,59.12,65.87,ZCTA5,57485.0
25,2509300.0,PALMER,Palmer,0,PALMER,HAMPDEN,1069.0,Massachusetts,MA,56.45,61.10,ZCTA5,59211.0
26,2510920.0,SOUTH HADLEY,South Hadley,0,SOUTH HADLEY,HAMPSHIRE,1075.0,Massachusetts,MA,69.03,68.40,ZCTA5,66681.0
27,2500013.0,SOUTHWICK-TOLLAND,Southwick-Tolland,0,SOUTHWICK,HAMPDEN,1077.0,Massachusetts,MA,71.57,70.70,ZCTA5,76737.0
28,2505430.0,GRANVILLE,Granville,0,SOUTHWICK,HAMPDEN,1077.0,Massachusetts,MA,70.78,66.51,ZCTA5,76737.0
29,2512030.0,WARE,Ware,0,WARE,HAMPSHIRE,1082.0,Massachusetts,MA,68.53,58.90,ZCTA5,51768.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13052,200007.0,ALEUTIANS EAST BOROUGH SCHOOL DISTRICT,Aleutians East,0,SAND POINT,ALEUTIANS EAST,99661.0,Alaska,AK,37.77,36.40,ZCTA5,68750.0
13053,200390.0,KENAI PENINSULA BOROUGH SCHOOL DISTRICT,Kenai Penin,0,SOLDOTNA,KENAI PENINSULA,99669.0,Alaska,AK,57.36,56.16,ZCTA5,77382.0
13054,200020.0,BERING STRAIT SCHOOL DISTRICT,Bering Strait,0,UNALAKLEET,NOME,99684.0,Alaska,AK,20.47,11.86,ZCTA5,65208.0
13055,200720.0,UNALASKA CITY SCHOOL DISTRICT,Unalaska,0,UNALASKA,ALEUTIANS WEST,99685.0,Alaska,AK,66.36,54.42,ZCTA5,92292.0
13056,200780.0,VALDEZ CITY SCHOOL DISTRICT,Valdez,0,VALDEZ,VALDEZ-CORDOVA,99686.0,Alaska,AK,56.86,55.34,ZCTA5,93940.0
13057,200840.0,YAKUTAT SCHOOL DISTRICT,Yakutat,0,YAKUTAT,YAKUTAT,99689.0,Alaska,AK,50.93,38.71,ZCTA5,64583.0
13058,200600.0,FAIRBANKS NORTH STAR BOROUGH SCHOOL DISTRICT,Fairbanks North Star,0,FAIRBANKS,FAIRBANKS NORTH STAR,99701.0,Alaska,AK,55.31,49.29,ZCTA5,58275.0
13059,200862.0,YUKON/KOYUKUK SCHOOL DISTRICT,Yukon Koyukuk,0,FAIRBANKS,FAIRBANKS NORTH STAR,99709.0,Alaska,AK,41.37,36.40,ZCTA5,84175.0
13060,200610.0,NORTH SLOPE BOROUGH SCHOOL DISTRICT,North Slope,0,BARROW,NORTH SLOPE,99723.0,Alaska,AK,39.70,24.82,ZCTA5,82964.0
13061,200100.0,DELTA/GREELY SCHOOL DISTRICT,Delta/Greely,0,DELTA JUNCTION,SOUTHEAST FAIRBANKS,99737.0,Alaska,AK,49.79,52.74,ZCTA5,75114.0
13062,200130.0,GALENA CITY SCHOOL DISTRICT,Galena City,0,GALENA,YUKON-KOYUKUK,99741.0,Alaska,AK,41.36,45.81,ZCTA5,74375.0
13063,200770.0,DENALI BOROUGH SCHOOL DISTRICT,Denali,0,HEALY,DENALI,99743.0,Alaska,AK,54.57,49.49,ZCTA5,90750.0
13064,200625.0,NORTHWEST ARCTIC BOROUGH SCHOOL DISTRICT,Northwest Arctic,0,KOTZEBUE,NORTHWEST ARCTIC,99752.0,Alaska,AK,28.82,17.53,ZCTA5,88047.0
13065,200540.0,NENANA CITY SCHOOL DISTRICT,Nenana,0,NENANA,YUKON-KOYUKUK,99760.0,Alaska,AK,40.75,51.04,ZCTA5,55536.0
13066,200570.0,NOME PUBLIC SCHOOLS,Nome Public Schools,0,NOME,NOME,99762.0,Alaska,AK,33.43,24.81,ZCTA5,79292.0
13067,200050.0,ALASKA GATEWAY SCHOOL DISTRICT,Alaska Gateway,0,TOK,SOUTHEAST FAIRBANKS,99780.0,Alaska,AK,44.34,42.79,ZCTA5,57500.0
13068,200210.0,JUNEAU BOROUGH SCHOOL DISTRICT,Juneau,0,JUNEAU,JUNEAU,99801.0,Alaska,AK,53.20,47.32,ZCTA5,91743.0
13069,200730.0,CHATHAM SCHOOL DISTRICT,Chatham,0,ANGOON,SKAGWAY-HOONAH-ANGOON,99820.0,Alaska,AK,12.75,21.39,ZCTA5,36000.0
13070,200270.0,HAINES BOROUGH SCHOOL DISTRICT,Haines,0,HAINES,HAINES,99827.0,Alaska,AK,56.83,49.49,ZCTA5,70091.0
13071,200300.0,HOONAH CITY SCHOOL DISTRICT,Hoonah,0,HOONAH,SKAGWAY-HOONAH-ANGOON,99829.0,Alaska,AK,50.45,31.97,ZCTA5,60625.0
13072,200360.0,KAKE CITY SCHOOL DISTRICT,Kake,0,KAKE,WRANGELL-PETERSBURG,99830.0,Alaska,AK,58.55,54.18,ZCTA5,51250.0
13073,200660.0,PETERSBURG CITY SCHOOL DISTRICT,Petersburg,0,PETERSBURG,WRANGELL-PETERSBURG,99833.0,Alaska,AK,58.97,58.77,ZCTA5,63490.0
13074,200240.0,SITKA SCHOOL DISTRICT,Sitka,0,SITKA,SITKA,99835.0,Alaska,AK,58.12,56.69,ZCTA5,70765.0
13075,200006.0,MOUNT EDGECUMBE HIGH SCHOOL,Mount Edgecumbe,0,SITKA,SITKA,99835.0,Alaska,AK,48.29,61.33,ZCTA5,70765.0
13076,200690.0,SKAGWAY CITY SCHOOL DISTRICT,Skagway,0,SKAGWAY,SKAGWAY-HOONAH-ANGOON,99840.0,Alaska,AK,64.15,68.91,ZCTA5,70673.0
13077,200150.0,KETCHIKAN GATEWAY BOROUGH SCHOOL DISTRICT,Ketchikan Gateway,0,KETCHIKAN,KETCHIKAN GATEWAY,99901.0,Alaska,AK,48.82,46.70,ZCTA5,67321.0
13078,200090.0,CRAIG CITY SCHOOL DISTRICT,Craig,0,CRAIG,PRINCE OF WALES-OUTER KETCHIKA,99921.0,Alaska,AK,52.73,50.70,ZCTA5,58047.0
13079,200450.0,KLAWOCK CITY SCHOOL DISTRICT,Klawock,0,KLAWOCK,PRINCE OF WALES-OUTER KETCHIKA,99925.0,Alaska,AK,40.84,39.87,ZCTA5,48646.0
13080,200525.0,ANNETTE ISLAND SCHOOL DISTRICT,Annette Island,0,METLAKATLA,PRINCE OF WALES-OUTER KETCHIKA,99926.0,Alaska,AK,44.64,44.54,ZCTA5,57969.0
13081,200810.0,WRANGELL PUBLIC SCHOOL DISTRICT,Wrangell Public,0,WRANGELL,WRANGELL-PETERSBURG,99929.0,Alaska,AK,63.67,57.15,ZCTA5,55742.0